### ISSUE TITLE
Foreign Keys is Databasen

### ISSUE THREAD

**Issue by Matttuu** [Matttuu/LMBank#1]
Når der oprettes ny bruger i databasen ( ie. admin) så giver den en fejl.

**Comment by dani832m** [comment]
ERROR 1452: 1452: Cannot add or update a child row: a foreign key constraint fails (`n4_dk_db`.`Users`, CONSTRAINT `fk_account` FOREIGN KEY (`fk_account`) REFERENCES `Accounts` (`account_id`) ON DELETE NO ACTION ON UPDATE NO ACTION)
